version: 2.1

jobs:
  build:
    docker:
      - image: "ubuntu:19.10"
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Install GIT
          command: 'apt-get update && sudo apt-get install -y git'
      - run:
          name: Install npm
          command: 'apt-get update && sudo apt-get install -y npm'
      - run:
          name: Install lftp
          command: 'apt-get update && sudo apt-get install -y lftp'
      - run:
          name: Update npm
          command: 'npm install -g npm'
      - run:
          command: |
            npm -v
            source ~/.bashrc
            npm install -g npm
            hash -r
            source ~/.bashrc
      - run:
          command: |
            npm install
            npm run build
            lftp -c "set ssl:verify-certificate no; open -u ${ftpusername},${ftppassword} ${ftpaddress}; rm -rf .; mirror -R build/ .; quit"
